name: fcpay
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  adaptive_theme: ^3.4.1
  bloc: ^8.1.2
  chopper: ^7.0.8
  equatable: ^2.0.5
  fl_chart: ^0.64.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.6.0
  formz: ^0.6.1
  gap: ^3.0.1
  go_router: ^11.1.4
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  permission_handler: ^11.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  recase: ^4.1.0
  responsive_framework: ^1.1.1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4
  go_router_builder: ^2.3.3
  flutter_gen_runner: ^5.2.0
  chopper_generator: ^7.0.6
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSerif-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSerif-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSerif-Regular.ttf
          weight: 400
    - family: NotoSansDisplay
      fonts:
        - asset: assets/fonts/NotoSansDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansDisplay-SemiBold.ttf
          weight: 600
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  output: lib/src/ui/generated
  line_length: 80

  integrations:
    flutter_svg: true