name: fcpay
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  chopper: ^7.0.8
  equatable: ^2.0.5
  fl_chart: ^0.64.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^11.1.4
  hydrated_bloc: ^9.1.2
  json_annotation: ^4.8.1
  permission_handler: ^11.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4
  go_router_builder: ^2.3.3
  chopper_generator: ^7.0.6
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
